---
name: Crypt-FNA
version: 0.24
author:
  - 'Mario Rossano aka Anak <software@netlogicalab.com>'
abstract: Fractal Numerical Algorithm - FNA - a new symmetric fractal encryption method
license: perl
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Crypt::FNA:
    file: lib/Crypt/FNA.pm
    version: 0.24
  Crypt::FNA::Validation:
    file: lib/Crypt/FNA/Validation.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
